"""초기 마스터 데이터. 수정 후 DB 파일(bangguseok.db)을 지우고 서버를 재시작하면 반영된다."""

from app.features.gamification.rules import BadgeCondition
from app.features.ingredients.models import StorageType as S
from app.features.recipes.models import Cookware, Difficulty

# (이름, 아이콘) — [화면 0] 온보딩 순서대로
SEASONINGS = [
    ("간장", "🫙"),
    ("식용유", "🛢️"),
    ("소금", "🧂"),
    ("후추", "🌶️"),
    ("설탕", "🍬"),
    ("고추장", "🥫"),
    ("된장", "🥣"),
    ("참기름", "🫗"),
    ("고춧가루", "🌶️"),
    ("다진마늘", "🧄"),
    ("마요네즈", "🥚"),
    ("케첩", "🍅"),
]

# (이름, 아이콘, 보관, 소비기한(일), 기본수량, 단위, 자주쓰는재료)
PRESETS = [
    ("계란", "🥚", S.FRIDGE, 21, 10, "개", True),
    ("두부", "🧊", S.FRIDGE, 7, 1, "모", True),
    ("대파", "🌿", S.FRIDGE, 10, 1, "단", True),
    ("양파", "🧅", S.ROOM, 30, 2, "개", True),
    ("우유", "🥛", S.FRIDGE, 10, 1, "개", True),
    ("김치", "🥬", S.FRIDGE, 30, 1, "통", True),
    ("돼지고기", "🥩", S.FRIDGE, 4, 300, "g", True),
    ("스팸", "🥫", S.ROOM, 365, 1, "캔", True),
    ("감자", "🥔", S.ROOM, 30, 3, "개", False),
    ("당근", "🥕", S.FRIDGE, 21, 1, "개", False),
    ("애호박", "🥒", S.FRIDGE, 7, 1, "개", False),
    ("버섯", "🍄", S.FRIDGE, 5, 1, "팩", False),
    ("쪽파", "🌱", S.FRIDGE, 7, 1, "단", False),
    ("소시지", "🌭", S.FRIDGE, 14, 1, "봉", False),
    ("햄", "🍖", S.FRIDGE, 14, 1, "개", False),
    ("참치캔", "🐟", S.ROOM, 365, 1, "캔", False),
    ("닭가슴살", "🍗", S.FRIDGE, 3, 1, "팩", False),
    ("소고기", "🥩", S.FRIDGE, 3, 200, "g", False),
    ("냉동만두", "🥟", S.FREEZER, 180, 1, "봉", False),
    ("밥", "🍚", S.FREEZER, 30, 2, "공기", False),
    ("라면", "🍜", S.ROOM, 150, 1, "개", False),
    ("치즈", "🧀", S.FRIDGE, 30, 1, "봉", False),
    ("콩나물", "🌱", S.FRIDGE, 3, 1, "봉", False),
    ("어묵", "🍢", S.FRIDGE, 7, 1, "봉", False),
    ("떡", "🍡", S.FRIDGE, 5, 1, "봉", False),
    ("고추", "🌶️", S.FRIDGE, 10, 3, "개", False),
    ("마늘", "🧄", S.FRIDGE, 14, 1, "봉", False),
]

# 재료: (이름, 수량, 단위, 양념여부, 선택여부, 대체재) — 수량은 1인분 기준, None 이면 '약간/적당량'
# 재료 이름은 ingredient_presets / seasonings 의 이름과 똑같이 써야 매칭된다.
RECIPES = [
    # ---------- 찌개 · 국 ----------
    {
        "title": "김치찌개",
        "description": "김치와 돼지고기만 있으면 끓이는 자취 대표 찌개",
        "cook_minutes": 25,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.POT,
        "ingredients": [
            ("김치", 1, "컵", False, False, []),
            ("돼지고기", 100, "g", False, False, ["스팸", "참치캔"]),
            ("두부", 0.5, "모", False, True, []),
            ("대파", 0.5, "대", False, True, ["쪽파", "양파"]),
            ("고춧가루", 1, "큰술", True, True, []),
            ("다진마늘", 1, "작은술", True, True, []),
        ],
        "steps": [
            "냄비에 돼지고기와 김치를 넣고 중불에서 3분간 볶아요.",
            "물 2컵을 붓고 고춧가루·다진마늘을 넣어 끓여요.",
            "끓어오르면 두부와 대파를 넣고 5분 더 끓이면 완성!",
        ],
    },
    {
        "title": "된장찌개",
        "description": "냉장고 속 자투리 채소를 한 번에 정리하는 된장찌개",
        "cook_minutes": 20,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.POT,
        "ingredients": [
            ("두부", 0.5, "모", False, False, []),
            ("애호박", 0.3, "개", False, False, ["감자", "버섯"]),
            ("양파", 0.3, "개", False, True, []),
            ("버섯", 0.3, "팩", False, True, []),
            ("대파", 0.3, "대", False, True, ["쪽파"]),
            ("된장", 1.5, "큰술", True, False, []),
            ("다진마늘", 0.5, "작은술", True, True, []),
        ],
        "steps": [
            "냄비에 물 2컵을 붓고 된장을 풀어 끓여요.",
            "애호박·양파·버섯을 한입 크기로 썰어 넣고 5분 끓여요.",
            "두부와 다진마늘, 대파를 넣고 3분 더 끓이면 완성!",
        ],
    },
    {
        "title": "부대찌개",
        "description": "햄·소시지·김치로 만드는 든든한 찌개",
        "cook_minutes": 20,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.POT,
        "ingredients": [
            ("햄", 0.5, "개", False, False, ["스팸"]),
            ("소시지", 2, "개", False, False, ["햄", "스팸"]),
            ("김치", 0.5, "컵", False, False, []),
            ("대파", 0.5, "대", False, True, ["양파"]),
            ("두부", 0.3, "모", False, True, []),
            ("라면", 0.5, "개", False, True, []),
            ("고추장", 1, "큰술", True, False, []),
            ("고춧가루", 1, "큰술", True, True, []),
            ("다진마늘", 1, "작은술", True, True, []),
        ],
        "steps": [
            "햄·소시지·두부·대파를 먹기 좋게 썰어요.",
            "냄비에 재료와 김치를 담고 고추장·고춧가루·다진마늘을 올려요.",
            "물 2컵을 붓고 끓이다가 라면 사리를 넣어 2분 더 끓이면 완성!",
        ],
    },
    {
        "title": "계란국",
        "description": "5분이면 끝나는 부드러운 국",
        "cook_minutes": 10,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.POT,
        "ingredients": [
            ("계란", 2, "개", False, False, []),
            ("대파", 0.3, "대", False, True, ["쪽파"]),
            ("소금", None, "약간", True, False, []),
            ("간장", 0.5, "큰술", True, True, []),
            ("다진마늘", 0.5, "작은술", True, True, []),
        ],
        "steps": [
            "냄비에 물 2컵을 끓이고 간장·다진마늘·소금으로 간해요.",
            "풀어둔 계란을 끓는 물에 천천히 둘러 부어요.",
            "송송 썬 대파를 넣고 한 번 더 끓이면 완성!",
        ],
    },
    {
        "title": "콩나물국",
        "description": "시원하고 칼칼한 해장국",
        "cook_minutes": 15,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.POT,
        "ingredients": [
            ("콩나물", 0.5, "봉", False, False, []),
            ("대파", 0.3, "대", False, True, ["쪽파"]),
            ("소금", None, "약간", True, False, []),
            ("다진마늘", 0.5, "작은술", True, True, []),
            ("고춧가루", 0.5, "작은술", True, True, []),
        ],
        "steps": [
            "냄비에 물 2컵과 씻은 콩나물을 넣고 뚜껑을 덮어 5분 끓여요.",
            "뚜껑을 열고 다진마늘·소금으로 간해요.",
            "대파와 고춧가루를 넣고 1분 더 끓이면 완성!",
        ],
    },
    {
        "title": "만둣국",
        "description": "냉동만두로 만드는 간단한 한 그릇",
        "cook_minutes": 12,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.POT,
        "ingredients": [
            ("냉동만두", 6, "개", False, False, []),
            ("계란", 1, "개", False, True, []),
            ("대파", 0.3, "대", False, True, ["쪽파"]),
            ("간장", 1, "큰술", True, False, []),
            ("다진마늘", 0.5, "작은술", True, True, []),
        ],
        "steps": [
            "냄비에 물 2컵을 끓이고 간장·다진마늘로 간해요.",
            "냉동만두를 넣고 만두가 떠오를 때까지 5분 끓여요.",
            "계란을 풀어 넣고 대파를 올리면 완성!",
        ],
    },
    # ---------- 밥 · 덮밥 ----------
    {
        "title": "김치볶음밥",
        "description": "남은 밥과 김치로 만드는 자취 필수 메뉴",
        "cook_minutes": 15,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("밥", 1, "공기", False, False, []),
            ("김치", 0.5, "컵", False, False, []),
            ("계란", 1, "개", False, True, []),
            ("스팸", 0.3, "캔", False, True, ["햄", "소시지"]),
            ("식용유", 1, "큰술", True, False, []),
            ("참기름", 0.5, "큰술", True, True, []),
        ],
        "steps": [
            "김치와 스팸을 잘게 썰어 기름 두른 팬에 볶아요.",
            "밥을 넣고 골고루 볶은 뒤 참기름을 둘러요.",
            "계란 프라이를 올리면 완성!",
        ],
    },
    {
        "title": "양파 계란덮밥",
        "cook_minutes": 15,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("밥", 1, "공기", False, False, []),
            ("양파", 0.5, "개", False, False, []),
            ("계란", 2, "개", False, False, []),
            ("간장", 2, "큰술", True, False, []),
            ("설탕", 1, "큰술", True, False, []),
        ],
        "steps": [
            "양파를 채 썰어 간장·설탕·물 4큰술과 함께 팬에서 졸여요.",
            "양파가 투명해지면 풀어둔 계란을 둘러 반숙으로 익혀요.",
            "밥 위에 올리면 완성!",
        ],
    },
    {
        "title": "스팸마요덮밥",
        "cook_minutes": 10,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("밥", 1, "공기", False, False, []),
            ("스팸", 0.3, "캔", False, False, ["햄", "참치캔"]),
            ("계란", 1, "개", False, False, []),
            ("마요네즈", None, "적당량", True, False, []),
            ("간장", 1, "큰술", True, False, []),
        ],
        "steps": [
            "스팸을 깍둑썰기해 노릇하게 구워요.",
            "계란은 스크램블로 익혀요.",
            "밥 위에 스팸·계란을 올리고 간장과 마요네즈를 뿌려요.",
        ],
    },
    {
        "title": "참치마요덮밥",
        "description": "불 없이 3분 만에 완성",
        "cook_minutes": 5,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ANY,
        "ingredients": [
            ("밥", 1, "공기", False, False, []),
            ("참치캔", 1, "캔", False, False, []),
            ("양파", 0.2, "개", False, True, []),
            ("마요네즈", 2, "큰술", True, False, []),
            ("간장", 0.5, "큰술", True, False, []),
        ],
        "steps": [
            "참치캔의 기름을 빼고 잘게 다진 양파, 마요네즈와 섞어요.",
            "밥 위에 참치마요를 올려요.",
            "간장을 살짝 둘러 비벼 먹으면 완성!",
        ],
    },
    {
        "title": "대파 계란볶음밥",
        "cook_minutes": 15,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("밥", 1, "공기", False, False, []),
            ("대파", 1, "대", False, False, ["쪽파", "양파"]),
            ("계란", 2, "개", False, False, []),
            ("간장", 1, "큰술", True, False, []),
            ("식용유", 2, "큰술", True, False, []),
        ],
        "steps": [
            "기름에 송송 썬 대파를 볶아 파기름을 내요.",
            "계란을 넣어 스크램블한 뒤 밥을 넣고 볶아요.",
            "팬 가장자리에 간장을 눌러 향을 입히면 완성!",
        ],
    },
    {
        "title": "소고기덮밥",
        "description": "달짝지근한 간장 소스의 규동 스타일 덮밥",
        "cook_minutes": 15,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("밥", 1, "공기", False, False, []),
            ("소고기", 100, "g", False, False, ["돼지고기"]),
            ("양파", 0.5, "개", False, False, []),
            ("계란", 1, "개", False, True, []),
            ("간장", 2, "큰술", True, False, []),
            ("설탕", 1, "큰술", True, False, []),
        ],
        "steps": [
            "팬에 물 5큰술, 간장, 설탕을 넣고 채 썬 양파를 끓여요.",
            "양파가 숨이 죽으면 소고기를 넣고 익혀요.",
            "밥 위에 올리고 노른자나 계란 프라이를 곁들이면 완성!",
        ],
    },
    # ---------- 반찬 · 볶음 ----------
    {
        "title": "두부 계란부침",
        "cook_minutes": 15,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("두부", 1, "모", False, False, []),
            ("계란", 2, "개", False, False, []),
            ("대파", None, "약간", False, False, ["쪽파", "양파"]),
            ("간장", 1, "큰술", True, False, []),
            ("식용유", 2, "큰술", True, False, []),
        ],
        "steps": [
            "두부를 1cm 두께로 썰고 키친타월로 물기를 제거해요.",
            "계란을 풀고 다진 대파를 섞어 계란물을 만들어요.",
            "두부에 계란물을 입혀 기름 두른 팬에 앞뒤로 노릇하게 부쳐요.",
        ],
    },
    {
        "title": "두부조림",
        "description": "밥도둑 매콤달콤 두부조림",
        "cook_minutes": 20,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("두부", 1, "모", False, False, []),
            ("대파", 0.3, "대", False, True, ["쪽파"]),
            ("양파", 0.3, "개", False, True, []),
            ("간장", 2, "큰술", True, False, []),
            ("고춧가루", 1, "큰술", True, True, []),
            ("설탕", 0.5, "큰술", True, False, []),
            ("다진마늘", 0.5, "큰술", True, True, []),
            ("식용유", 1, "큰술", True, False, []),
        ],
        "steps": [
            "두부를 도톰하게 썰어 기름 두른 팬에 앞뒤로 구워요.",
            "간장·고춧가루·설탕·다진마늘·물 5큰술을 섞어 양념장을 만들어요.",
            "두부 위에 양념장과 양파·대파를 올리고 약불에서 5분 졸이면 완성!",
        ],
    },
    {
        "title": "계란말이",
        "cook_minutes": 10,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("계란", 3, "개", False, False, []),
            ("양파", 0.25, "개", False, True, ["대파", "쪽파"]),
            ("소금", None, "약간", True, False, []),
            ("식용유", 1, "큰술", True, False, []),
        ],
        "steps": [
            "계란을 풀고 잘게 다진 양파와 소금을 넣어 섞어요.",
            "약불로 달군 팬에 계란물을 얇게 부어요.",
            "반쯤 익으면 돌돌 말고, 남은 계란물을 부어가며 반복해요.",
        ],
    },
    {
        "title": "치즈 스크램블에그",
        "description": "아침에 딱 좋은 부드러운 스크램블",
        "cook_minutes": 5,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("계란", 2, "개", False, False, []),
            ("우유", 2, "큰술", False, True, []),
            ("치즈", 1, "장", False, True, []),
            ("소금", None, "약간", True, False, []),
            ("식용유", 0.5, "큰술", True, False, []),
        ],
        "steps": [
            "계란에 우유와 소금을 넣고 잘 풀어요.",
            "약불로 달군 팬에 붓고 젓가락으로 천천히 저어가며 익혀요.",
            "반쯤 익으면 치즈를 올리고 불을 끈 뒤 잔열로 녹이면 완성!",
        ],
    },
    {
        "title": "애호박전",
        "cook_minutes": 15,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("애호박", 0.5, "개", False, False, []),
            ("계란", 1, "개", False, False, []),
            ("소금", None, "약간", True, False, []),
            ("식용유", 2, "큰술", True, False, []),
        ],
        "steps": [
            "애호박을 0.5cm 두께로 동그랗게 썰고 소금을 살짝 뿌려요.",
            "애호박에 풀어둔 계란물을 입혀요.",
            "기름 두른 팬에 앞뒤로 노릇하게 부치면 완성!",
        ],
    },
    {
        "title": "감자볶음",
        "cook_minutes": 15,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("감자", 1, "개", False, False, []),
            ("양파", 0.3, "개", False, True, []),
            ("당근", 0.2, "개", False, True, []),
            ("소금", None, "약간", True, False, []),
            ("식용유", 1.5, "큰술", True, False, []),
        ],
        "steps": [
            "감자·양파·당근을 가늘게 채 썰고 감자는 물에 헹궈 전분을 빼요.",
            "기름 두른 팬에 감자를 먼저 3분 볶아요.",
            "양파·당근을 넣고 소금으로 간해 2분 더 볶으면 완성!",
        ],
    },
    {
        "title": "버섯볶음",
        "cook_minutes": 10,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("버섯", 1, "팩", False, False, []),
            ("양파", 0.3, "개", False, True, []),
            ("간장", 1, "큰술", True, False, []),
            ("참기름", 0.5, "큰술", True, True, []),
            ("다진마늘", 0.5, "작은술", True, True, []),
            ("식용유", 1, "큰술", True, False, []),
        ],
        "steps": [
            "버섯은 먹기 좋게 찢고 양파는 채 썰어요.",
            "기름 두른 팬에 다진마늘과 양파를 볶다가 버섯을 넣어요.",
            "간장으로 간하고 참기름을 둘러 마무리하면 완성!",
        ],
    },
    {
        "title": "어묵볶음",
        "cook_minutes": 10,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("어묵", 2, "장", False, False, []),
            ("양파", 0.3, "개", False, True, []),
            ("당근", 0.2, "개", False, True, []),
            ("간장", 1, "큰술", True, False, []),
            ("설탕", 0.5, "큰술", True, False, []),
            ("식용유", 1, "큰술", True, False, []),
        ],
        "steps": [
            "어묵과 채소를 먹기 좋게 썰어요.",
            "기름 두른 팬에 양파·당근을 볶다가 어묵을 넣어요.",
            "간장·설탕·물 2큰술을 넣고 윤기 나게 볶으면 완성!",
        ],
    },
    {
        "title": "소시지야채볶음",
        "description": "케첩 소스로 만드는 쏘야",
        "cook_minutes": 12,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("소시지", 5, "개", False, False, ["햄"]),
            ("양파", 0.5, "개", False, False, []),
            ("당근", 0.2, "개", False, True, []),
            ("케첩", 2, "큰술", True, False, []),
            ("설탕", 0.5, "큰술", True, True, []),
            ("식용유", 1, "큰술", True, False, []),
        ],
        "steps": [
            "소시지에 칼집을 내고 채소를 한입 크기로 썰어요.",
            "기름 두른 팬에 채소와 소시지를 볶아요.",
            "케첩·설탕을 넣고 1분 더 볶으면 완성!",
        ],
    },
    {
        "title": "제육볶음",
        "description": "고추장 양념의 매콤한 돼지고기 볶음",
        "cook_minutes": 20,
        "difficulty": Difficulty.NORMAL,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("돼지고기", 150, "g", False, False, []),
            ("양파", 0.5, "개", False, False, []),
            ("대파", 0.3, "대", False, True, ["쪽파"]),
            ("고추", 1, "개", False, True, []),
            ("고추장", 1.5, "큰술", True, False, []),
            ("간장", 1, "큰술", True, False, []),
            ("설탕", 1, "큰술", True, False, []),
            ("다진마늘", 1, "작은술", True, True, []),
            ("식용유", 1, "큰술", True, False, []),
        ],
        "steps": [
            "돼지고기에 고추장·간장·설탕·다진마늘을 넣어 10분 재워요.",
            "기름 두른 팬에 고기를 볶다가 반쯤 익으면 양파를 넣어요.",
            "대파·고추를 넣고 1분 더 볶으면 완성!",
        ],
    },
    {
        "title": "닭가슴살 간장볶음",
        "description": "퍽퍽하지 않게 먹는 닭가슴살",
        "cook_minutes": 15,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.ONE_PAN,
        "ingredients": [
            ("닭가슴살", 1, "팩", False, False, []),
            ("양파", 0.5, "개", False, False, []),
            ("대파", 0.3, "대", False, True, ["쪽파"]),
            ("간장", 1.5, "큰술", True, False, []),
            ("설탕", 0.5, "큰술", True, False, []),
            ("다진마늘", 0.5, "작은술", True, True, []),
            ("식용유", 1, "큰술", True, False, []),
        ],
        "steps": [
            "닭가슴살을 한입 크기로 썰고 양파는 채 썰어요.",
            "기름 두른 팬에 닭가슴살을 볶아 익혀요.",
            "양파와 간장·설탕·다진마늘을 넣고 졸이듯 볶은 뒤 대파를 올리면 완성!",
        ],
    },
    {
        "title": "떡볶이",
        "cook_minutes": 20,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.POT,
        "ingredients": [
            ("떡", 1, "봉", False, False, []),
            ("어묵", 1, "장", False, True, []),
            ("대파", 0.5, "대", False, True, ["양파"]),
            ("계란", 1, "개", False, True, []),
            ("고추장", 2, "큰술", True, False, []),
            ("설탕", 1, "큰술", True, False, []),
            ("고춧가루", 0.5, "큰술", True, True, []),
        ],
        "steps": [
            "냄비에 물 1.5컵과 고추장·설탕·고춧가루를 풀어 끓여요.",
            "떡과 어묵을 넣고 중불에서 저어가며 7분 끓여요.",
            "대파와 삶은 계란을 넣고 국물이 걸쭉해지면 완성!",
        ],
    },
    {
        "title": "콩나물무침",
        "cook_minutes": 10,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.POT,
        "ingredients": [
            ("콩나물", 0.5, "봉", False, False, []),
            ("대파", 0.2, "대", False, True, ["쪽파"]),
            ("소금", None, "약간", True, False, []),
            ("참기름", 1, "큰술", True, False, []),
            ("다진마늘", 0.5, "작은술", True, True, []),
        ],
        "steps": [
            "끓는 물에 콩나물을 넣고 뚜껑을 덮은 채 4분 데쳐요.",
            "찬물에 헹궈 물기를 꼭 짜요.",
            "소금·참기름·다진마늘·대파를 넣고 조물조물 무치면 완성!",
        ],
    },
    # ---------- 전자레인지 · 간편 ----------
    {
        "title": "두부계란찜",
        "cook_minutes": 12,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.MICROWAVE,
        "ingredients": [
            ("두부", 0.5, "모", False, False, []),
            ("계란", 2, "개", False, False, []),
            ("대파", None, "약간", False, True, ["쪽파"]),
            ("소금", None, "약간", True, False, []),
        ],
        "steps": [
            "두부를 으깨고 계란·물 3큰술·소금을 넣어 잘 섞어요.",
            "전자레인지용 그릇에 담고 대파를 올려요.",
            "랩을 씌워 전자레인지에 3~4분 돌리면 완성!",
        ],
    },
    {
        "title": "전자레인지 계란찜",
        "description": "그릇 하나로 끝내는 폭신한 계란찜",
        "cook_minutes": 5,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.MICROWAVE,
        "ingredients": [
            ("계란", 2, "개", False, False, []),
            ("대파", None, "약간", False, True, ["쪽파"]),
            ("소금", None, "약간", True, False, []),
        ],
        "steps": [
            "전자레인지용 그릇에 계란 2개와 물 4큰술, 소금을 넣고 잘 풀어요.",
            "송송 썬 대파를 올리고 랩을 씌워 구멍을 몇 개 뚫어요.",
            "전자레인지에 2분 30초 돌리면 완성!",
        ],
    },
    {
        "title": "계란파라면",
        "description": "평범한 라면을 한 단계 업그레이드",
        "cook_minutes": 7,
        "difficulty": Difficulty.EASY,
        "cookware": Cookware.POT,
        "ingredients": [
            ("라면", 1, "개", False, False, []),
            ("계란", 1, "개", False, True, []),
            ("대파", 0.3, "대", False, True, ["쪽파"]),
            ("치즈", 1, "장", False, True, []),
        ],
        "steps": [
            "물 550ml를 끓이고 면과 스프를 넣어요.",
            "2분 뒤 계란을 넣고 휘젓지 않고 익혀요.",
            "대파와 치즈를 올려 30초 더 끓이면 완성!",
        ],
    },
]

# (코드, 이름, 설명, 아이콘, 조건, 목표치)
BADGES = [
    ("FRIDGE_CLEANER", "냉장고 클리너", "유통기한 내 재료 소진 10회", "🧹", BadgeCondition.SAVED_BEFORE_EXPIRY, 10),
    ("HOME_COOK_MASTER", "집밥 마스터", "요리 완료 10회", "🍳", BadgeCondition.COOK_COUNT, 10),
    ("STREAK_7", "7일 연속 기록", "7일 연속 관리", "🔥", BadgeCondition.STREAK_DAYS, 7),
    ("STREAK_30", "30일 연속", "30일 연속 관리", "🏆", BadgeCondition.STREAK_DAYS, 30),
    ("RECIPE_20", "레시피 20개 완성", "요리 완료 20회", "📖", BadgeCondition.COOK_COUNT, 20),
    ("PHOTO_10", "사진 등록 10회", "사진으로 재료 등록 10회", "📸", BadgeCondition.PHOTO_REGISTER_COUNT, 10),
]
