"""initial schema — Alembic 도입 전(39f7494) create_all 로 만들던 테이블 그대로.

기존 로컬 DB(alembic_version 표가 없는 DB)는 app/migrate.py 가 이 버전으로 표시(stamp)만 하고 넘어간다.

Revision ID: 0001
Revises:
Create Date: 2026-09-28 05:54:45.600640

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "badges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=16), nullable=True),
        sa.Column("condition", sa.String(length=30), nullable=False),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "ingredient_presets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("icon", sa.String(length=16), nullable=True),
        sa.Column("default_storage", sa.String(length=10), nullable=False),
        sa.Column("shelf_life_days", sa.Integer(), nullable=False),
        sa.Column("default_quantity", sa.Double(), nullable=False),
        sa.Column("default_unit", sa.String(length=10), nullable=False),
        sa.Column("is_frequent", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingredient_presets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ingredient_presets_name"), ["name"], unique=True)

    op.create_table(
        "seasonings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("icon", sa.String(length=16), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("nickname", sa.String(length=30), nullable=False),
        sa.Column("onboarded", sa.Boolean(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("best_streak", sa.Integer(), nullable=False),
        sa.Column("last_active_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_device_id"), ["device_id"], unique=True)

    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("preset_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("quantity", sa.Double(), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("storage", sa.String(length=10), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["preset_id"],
            ["ingredient_presets.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ingredients_expires_on"), ["expires_on"], unique=False)
        batch_op.create_index(batch_op.f("ix_ingredients_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_ingredients_user_id"), ["user_id"], unique=False)

    op.create_table(
        "notification_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("ref_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("body", sa.String(length=200), nullable=False),
        sa.Column("sent_on", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "type", "ref_id", "sent_on"),
    )
    with op.batch_alter_table("notification_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notification_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "push_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=300), nullable=False),
        sa.Column("platform", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    with op.batch_alter_table("push_devices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_push_devices_user_id"), ["user_id"], unique=False)

    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("image_url", sa.String(length=300), nullable=True),
        sa.Column("cook_minutes", sa.Integer(), nullable=False),
        sa.Column("difficulty", sa.String(length=10), nullable=False),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.Column("cookware", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipes_source"), ["source"], unique=False)

    op.create_table(
        "reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=40), nullable=False),
        sa.Column("repeat_type", sa.String(length=10), nullable=False),
        sa.Column("interval", sa.Integer(), nullable=False),
        sa.Column("weekdays", sa.JSON(), nullable=False),
        sa.Column("day_of_month", sa.Integer(), nullable=True),
        sa.Column("remind_time", sa.Time(), nullable=False),
        sa.Column("notify_before_days", sa.Integer(), nullable=False),
        sa.Column("anchor_date", sa.Date(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_done_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reminders_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_badges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("badge_id", sa.Integer(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["badge_id"], ["badges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "badge_id"),
    )
    with op.batch_alter_table("user_badges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_badges_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_seasonings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("seasoning_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["seasoning_id"], ["seasonings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "seasoning_id"),
    )
    with op.batch_alter_table("user_seasonings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_seasonings_user_id"), ["user_id"], unique=False)

    op.create_table(
        "xp_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("ref_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("xp_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_xp_logs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_xp_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "cook_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("xp_awarded", sa.Integer(), nullable=False),
        sa.Column("consumed_snapshot", sa.JSON(), nullable=False),
        sa.Column("undone_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cook_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cook_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "recipe_ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("quantity", sa.Double(), nullable=True),
        sa.Column("unit", sa.String(length=10), nullable=True),
        sa.Column("is_seasoning", sa.Boolean(), nullable=False),
        sa.Column("is_optional", sa.Boolean(), nullable=False),
        sa.Column("substitutes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipe_ingredients", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_ingredients_recipe_id"), ["recipe_id"], unique=False)

    op.create_table(
        "recipe_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("step_no", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipe_steps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_steps_recipe_id"), ["recipe_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_steps_recipe_id"))

    op.drop_table("recipe_steps")
    with op.batch_alter_table("recipe_ingredients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_ingredients_recipe_id"))

    op.drop_table("recipe_ingredients")
    with op.batch_alter_table("cook_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cook_logs_user_id"))

    op.drop_table("cook_logs")
    with op.batch_alter_table("xp_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_xp_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_xp_logs_created_at"))

    op.drop_table("xp_logs")
    with op.batch_alter_table("user_seasonings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_seasonings_user_id"))

    op.drop_table("user_seasonings")
    with op.batch_alter_table("user_badges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_badges_user_id"))

    op.drop_table("user_badges")
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminders_user_id"))

    op.drop_table("reminders")
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipes_source"))

    op.drop_table("recipes")
    with op.batch_alter_table("push_devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_push_devices_user_id"))

    op.drop_table("push_devices")
    with op.batch_alter_table("notification_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_logs_user_id"))

    op.drop_table("notification_logs")
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingredients_user_id"))
        batch_op.drop_index(batch_op.f("ix_ingredients_status"))
        batch_op.drop_index(batch_op.f("ix_ingredients_expires_on"))

    op.drop_table("ingredients")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_device_id"))

    op.drop_table("users")
    op.drop_table("seasonings")
    with op.batch_alter_table("ingredient_presets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingredient_presets_name"))

    op.drop_table("ingredient_presets")
    op.drop_table("badges")
    # ### end Alembic commands ###
